/**
 * 生成插件市场清单 index.json 与 README 插件表格
 * 遍历 plugin/<id>/plugin.json，输出统一目录
 * 运行：bun scripts/generate_catalog.ts
 */
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const root = process.cwd();
const pluginDir = join(root, 'plugin');
const base = 'https://raw.githubusercontent.com/MicYou-Dev/MicYou-Plugins/main';
const gh = 'https://github.com/MicYou-Dev/MicYou-Plugins/tree/main';

interface Manifest {
  id: string;
  name: string;
  version: string;
  author?: string;
  description?: string;
  runtime: string;
  kind?: string;
  capabilities?: string[];
  license?: string;
  homepage?: string;
  repository?: string;
  nameI18n?: Record<string, string>;
  descriptionI18n?: Record<string, string>;
  arches?: string[];
  platforms?: string[];
}

const entries: Manifest[] = [];
for (const dir of readdirSync(pluginDir).sort()) {
  const p = join(pluginDir, dir, 'plugin.json');
  if (!existsSync(p)) continue;
  const m = JSON.parse(readFileSync(p, 'utf8')) as Manifest;
  if (!m.id) continue;
  entries.push(m);
}

const catalog = {
  name: 'MicYou Plugins',
  description: 'MicYou 插件市场目录（应用内「检查更新」与本页面均读取此清单）',
  updatedAt: new Date().toISOString(),
  plugins: entries.map((m) => ({
    id: m.id,
    name: m.name,
    nameI18n: m.nameI18n ?? {},
    version: m.version,
    author: m.author ?? '',
    description: m.description ?? '',
    descriptionI18n: m.descriptionI18n ?? {},
    runtime: m.runtime,
    kind: m.kind ?? 'utility',
    capabilities: m.capabilities ?? [],
    license: m.license ?? '',
    homepage: m.homepage ?? '',
    repository: m.repository ?? '',
    manifestUrl: `${base}/plugin/${m.id}/plugin.json`,
    downloadUrl: `${base}/plugin/${m.id}/plugin.zip`,
    previewUrl: `${base}/plugin/${m.id}/preview.png`,
    pageUrl: `${gh}/plugin/${m.id}`,
    arches: m.arches ?? [],
    platforms: m.platforms ?? [],
  })),
};

writeFileSync(join(root, 'index.json'), JSON.stringify(catalog, null, 2) + '\n');

const rows = catalog.plugins
  .map(
    (p) =>
      `| [${p.name}](${p.pageUrl}) | \`${p.id}\` | ${p.runtime} | ${p.kind} | ${p.version} | ${p.author} | ${p.capabilities.length ? p.capabilities.join(', ') : '—'} | [zip](${p.downloadUrl}) |`,
  )
  .join('\n');

const readme = `# MicYou Plugins

<!-- Generated by scripts/generate_catalog.ts. Do not edit manually. -->

MicYou 的插件市场仓库：插件目录与打包产物

## 仓库结构

\`\`\`text
/
├── index.json                 # 自动生成的插件清单（应用内检查更新读取）
└── plugin/
    └── <plugin-id>/
        ├── plugin.json        # 插件 manifest（含 updateUrl 指向本仓库）
        ├── plugin.zip         # 打包产物（应用「导入插件」直接安装）
        └── README.md          # 可选：插件说明
\`\`\`

每个插件目录的 \`plugin.json\` 是元数据来源，\`index.json\` 与下方表格自动生成

应用内更新机制：插件声明 \`updateUrl\` 指向本仓库的 \`plugin.json\`，点「检查更新」
即做 semver 对比，有新版本一键下载 \`plugin.zip\` 覆盖安装

## 当前插件

| 名称 | ID | 运行时 | 类型 | 版本 | 作者 | 能力 | 下载 |
| --- | --- | --- | --- | --- | --- | --- | --- |
${rows}

## 贡献插件

想要发布插件，请阅读 [CONTRIBUTING.md](CONTRIBUTING.md)

## 生成

\`\`\`bash
bun scripts/generate_catalog.ts
\`\`\`

CI（generate-catalog.yml）在 push 时自动重新生成 index.json 与本文档
`;
writeFileSync(join(root, 'README.md'), readme);
console.log(`catalog: ${entries.length} plugins -> index.json + README`);
